image: maven:3.9-eclipse-temurin-25

stages:
  - build
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --show-version"

cache:
  key: maven-${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository/

# Compilation passes
build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean compile

# All tests pass
test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
